### ISSUE TITLE
Verify authorize roles on Auth service

### ISSUE THREAD

**Issue by juanpujol** [Beakyn/gsp-ui-common#7]
Passing something like this to the Auth Service should verify the user and stop the UI to load.

```
permissions: {
   roles: [
      'admin', 
      'author', 
      'editor', 
      'publisher'
   ],
   teams: [
      'sales',
      'real-estate'
   ]
}
```

**Comment by riconegri** [comment]
Taxonomy UI changes are on branch issue#29

**Comment by juanpujol** [comment]
Tests:

- [ ] If the UI has no `roles` defined on gsp config, any user with any role should be allowed to login.
- [ ] If the UI has `roles` defined on the gsp config, only users with those roles can login.
- [ ] If a user with a role different from the ones defined on `roles` in gsp config tries to login, it should be prevented. And just leave the login page open, clean localstorage and disable sso for the running app.
- [ ] Do not logout the user from the entire auth0 system.
